title: "Диалектическая психология благополучия"
description: "Психология благополучия через критическое мышление и материалистическую диалектику"
url: "https://dial-pos-psych.github.io"
baseurl: ""
lang: ru
yandex_metrika_id: 109387183
yandex_metrika_variant: pages
timezone: Europe/Moscow
encoding: utf-8
destination: _site
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- excerpt-disabled -->"

plugins:
  - jekyll-seo-tag

include:
  - .htaccess
  - .well-known

exclude:
  - _site
  - .venv
  - .bundle
  - .jekyll-cache
  - .jekyll-server.log
  - .gitignore
  - .ruby-version
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  posts:
    output: true
